---
- name: "Load lvm kernel modules"
  become: true
  with_items:
      - "dm_snapshot"
      - "dm_mirror"
      - "dm_thin_pool"
  modprobe:
      name: "{{ item }}"
      state: "present"

- name: "Install glusterfs mount utils"
  become: true
  yum:
      name: "glusterfs-fuse"
      state: "present"
