---
- name: "Create long term Heketi instance."
  command: "kubectl create -f {{ role_path }}/heketi-deployment.json"
- name: "Get heketi deployment state."
  register: "heketi_deployment_state"
  command: "kubectl get deployment heketi -o=name --ignore-not-found=true"
  changed_when: false
- name: "Ensure heketi is up and running."
  assert: { that: "heketi_deployment_state.stdout != \"\"", message: "Heketi deployment did not succeed." }

